[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ali"
description = "A simple cli tool to create and manage custom commands"
readme = "README.md"
version = "0.1.0"
dependencies = []
authors = [
    {name = "skueee", email = "skueee@outlook.com"}
]

[project.scripts]
ali = "ali.ali:main"
